/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

import Controller.AdminServerController;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class AdminServer extends javax.swing.JFrame {
    
    /**
     * Creates new form AdminFrame
     */
    public AdminServer() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Quản Lý");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        loadDateTimePickerBill();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_Admin = new javax.swing.JTabbedPane();
        jPanel_ad_Doanhthu = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jDateChooser_CheckIn = new com.toedter.calendar.JDateChooser();
        jDateChooser_CheckOut = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Thongke = new javax.swing.JTable();
        jPanel_ad_Thucan = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Food = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton_ad_ta_Timthucan = new javax.swing.JButton();
        jlabel_ad_ta_Timthucan = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel_ta_ID = new javax.swing.JLabel();
        jLabel_ta_Tenmon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_ad_ta_ID = new javax.swing.JTextField();
        jTextField_ad_ta_Tenmon = new javax.swing.JTextField();
        jComboBox_ad_ta_Danhmuc = new javax.swing.JComboBox<>();
        jSpinner_ad_ta_Gia = new javax.swing.JSpinner();
        jPanel11 = new javax.swing.JPanel();
        jButton_ad_ta_Them = new javax.swing.JButton();
        jButton_ad_ta_Xoa = new javax.swing.JButton();
        jButton_ad_ta_Sua = new javax.swing.JButton();
        jButton_ad_ta_Xem = new javax.swing.JButton();
        jPanel_ad_Danhmuc = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton_ta_dm_Them = new javax.swing.JButton();
        jButton_ta_dm_Xoa = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_Danhmuc = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_ad_Banan = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jButton_ta_dm_Them3 = new javax.swing.JButton();
        jButton_ta_dm_Xoa3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_Banan = new javax.swing.JTable();
        jPanel_ad_Taikhoan = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jButton_ad_tk_Them = new javax.swing.JButton();
        jButton_ad_tk_Xoa = new javax.swing.JButton();
        jButton_ad_tk_Xem = new javax.swing.JButton();
        jButton_ad_tk_Xoa1 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jTextField_ad_tk_Tentaikhoan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton_ad_tk_Datlaimatkhau = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_ad_tk = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane_Admin.setBackground(new java.awt.Color(223, 230, 233));
        jTabbedPane_Admin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTabbedPane_Admin.setPreferredSize(new java.awt.Dimension(471, 78));

        jPanel_ad_Doanhthu.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(223, 230, 233));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Thống kê");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDateChooser_CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jDateChooser_CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser_CheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser_CheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable_Thongke.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTable_Thongke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Số bàn", "Giảm giá(%)", "Tổng tiền", "Ngày nhận bàn", "Ngày trả bàn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Thongke.setRowHeight(25);
        jScrollPane1.setViewportView(jTable_Thongke);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_ad_DoanhthuLayout = new javax.swing.GroupLayout(jPanel_ad_Doanhthu);
        jPanel_ad_Doanhthu.setLayout(jPanel_ad_DoanhthuLayout);
        jPanel_ad_DoanhthuLayout.setHorizontalGroup(
            jPanel_ad_DoanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ad_DoanhthuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ad_DoanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_ad_DoanhthuLayout.setVerticalGroup(
            jPanel_ad_DoanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ad_DoanhthuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane_Admin.addTab("Doanh thu", jPanel_ad_Doanhthu);

        jPanel_ad_Thucan.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable_Food.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable_Food.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tên món", "Loại", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Food.setRowHeight(25);
        jTable_Food.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_FoodMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_Food);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_ad_ta_Timthucan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ad_ta_Timthucan.setText("Tìm");
        jButton_ad_ta_Timthucan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ad_ta_TimthucanActionPerformed(evt);
            }
        });

        jlabel_ad_ta_Timthucan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlabel_ad_ta_Timthucan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlabel_ad_ta_TimthucanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabel_ad_ta_Timthucan, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton_ad_ta_Timthucan, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_ad_ta_Timthucan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ad_ta_Timthucan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(223, 230, 233));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel_ta_ID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_ta_ID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_ta_ID.setText("ID:");

        jLabel_ta_Tenmon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_ta_Tenmon.setText("Tên món:");
        jLabel_ta_Tenmon.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel_ta_TenmonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Danh mục:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Giá:");

        jTextField_ad_ta_ID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextField_ad_ta_Tenmon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_ad_ta_Tenmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ad_ta_TenmonActionPerformed(evt);
            }
        });

        jComboBox_ad_ta_Danhmuc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox_ad_ta_Danhmuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ad_ta_DanhmucActionPerformed(evt);
            }
        });

        jSpinner_ad_ta_Gia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_ta_Tenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ta_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_ad_ta_Tenmon)
                            .addComponent(jTextField_ad_ta_ID)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_ad_ta_Danhmuc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner_ad_ta_Gia))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ad_ta_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ta_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ta_Tenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ad_ta_Tenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_ad_ta_Danhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_ad_ta_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_ad_ta_Them.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ad_ta_Them.setText("Thêm");
        jButton_ad_ta_Them.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_ad_ta_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ad_ta_ThemActionPerformed(evt);
            }
        });
        jPanel11.add(jButton_ad_ta_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 83, 51));

        jButton_ad_ta_Xoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ad_ta_Xoa.setText("Xóa");
        jButton_ad_ta_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ad_ta_XoaActionPerformed(evt);
            }
        });
        jPanel11.add(jButton_ad_ta_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 83, 51));

        jButton_ad_ta_Sua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ad_ta_Sua.setText("Sửa");
        jButton_ad_ta_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ad_ta_SuaActionPerformed(evt);
            }
        });
        jPanel11.add(jButton_ad_ta_Sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 83, 51));

        jButton_ad_ta_Xem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ad_ta_Xem.setText("Xem");
        jButton_ad_ta_Xem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ad_ta_XemActionPerformed(evt);
            }
        });
        jPanel11.add(jButton_ad_ta_Xem, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 83, 51));

        javax.swing.GroupLayout jPanel_ad_ThucanLayout = new javax.swing.GroupLayout(jPanel_ad_Thucan);
        jPanel_ad_Thucan.setLayout(jPanel_ad_ThucanLayout);
        jPanel_ad_ThucanLayout.setHorizontalGroup(
            jPanel_ad_ThucanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ad_ThucanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ad_ThucanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ad_ThucanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_ad_ThucanLayout.setVerticalGroup(
            jPanel_ad_ThucanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ad_ThucanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ad_ThucanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel_ad_ThucanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane_Admin.addTab("Thực đơn", jPanel_ad_Thucan);

        jPanel_ad_Danhmuc.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jButton_ta_dm_Them.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ta_dm_Them.setText("Thêm");
        jButton_ta_dm_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ta_dm_ThemActionPerformed(evt);
            }
        });

        jButton_ta_dm_Xoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ta_dm_Xoa.setText("Xóa");
        jButton_ta_dm_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ta_dm_XoaActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setText("Xem");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_ta_dm_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton_ta_dm_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ta_dm_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ta_dm_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable_Danhmuc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable_Danhmuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Tên danh mục"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Danhmuc.setRowHeight(25);
        jTable_Danhmuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DanhmucMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable_Danhmuc);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(223, 230, 233));
        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Tên danh mục:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(343, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_ad_DanhmucLayout = new javax.swing.GroupLayout(jPanel_ad_Danhmuc);
        jPanel_ad_Danhmuc.setLayout(jPanel_ad_DanhmucLayout);
        jPanel_ad_DanhmucLayout.setHorizontalGroup(
            jPanel_ad_DanhmucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ad_DanhmucLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ad_DanhmucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ad_DanhmucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_ad_DanhmucLayout.setVerticalGroup(
            jPanel_ad_DanhmucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ad_DanhmucLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ad_DanhmucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ad_DanhmucLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ad_DanhmucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane_Admin.addTab("Danh mục", jPanel_ad_Danhmuc);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jButton_ta_dm_Them3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ta_dm_Them3.setText("Thêm");
        jButton_ta_dm_Them3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ta_dm_Them3ActionPerformed(evt);
            }
        });

        jButton_ta_dm_Xoa3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ta_dm_Xoa3.setText("Xóa");
        jButton_ta_dm_Xoa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ta_dm_Xoa3ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton9.setText("Sửa");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton10.setText("Xem");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_ta_dm_Them3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton_ta_dm_Xoa3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ta_dm_Xoa3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ta_dm_Them3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(223, 230, 233));
        jPanel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("ID:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Tên bàn:");

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Trạng thái:");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jTextField4))
                .addGap(28, 28, 28))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable_Banan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable_Banan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Tên  bàn", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Banan.setRowHeight(25);
        jTable_Banan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_BananMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable_Banan);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(398, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_ad_BananLayout = new javax.swing.GroupLayout(jPanel_ad_Banan);
        jPanel_ad_Banan.setLayout(jPanel_ad_BananLayout);
        jPanel_ad_BananLayout.setHorizontalGroup(
            jPanel_ad_BananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_ad_BananLayout.setVerticalGroup(
            jPanel_ad_BananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane_Admin.addTab("Bàn ăn", jPanel_ad_Banan);

        jPanel_ad_Taikhoan.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_ad_Taikhoan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jButton_ad_tk_Them.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ad_tk_Them.setText("Thêm");
        jButton_ad_tk_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ad_tk_ThemActionPerformed(evt);
            }
        });

        jButton_ad_tk_Xoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ad_tk_Xoa.setText("Xóa");
        jButton_ad_tk_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ad_tk_XoaActionPerformed(evt);
            }
        });

        jButton_ad_tk_Xem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ad_tk_Xem.setText("Xem");
        jButton_ad_tk_Xem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ad_tk_XemActionPerformed(evt);
            }
        });

        jButton_ad_tk_Xoa1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ad_tk_Xoa1.setText("Sửa");
        jButton_ad_tk_Xoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ad_tk_Xoa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_ad_tk_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton_ad_tk_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton_ad_tk_Xoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton_ad_tk_Xem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ad_tk_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ad_tk_Xem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ad_tk_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ad_tk_Xoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel17.setBackground(new java.awt.Color(223, 230, 233));
        jPanel17.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextField_ad_tk_Tentaikhoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_ad_tk_Tentaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ad_tk_TentaikhoanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tên tài khoản:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Loại tài khoản:");

        jButton_ad_tk_Datlaimatkhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton_ad_tk_Datlaimatkhau.setText("Reset Account");
        jButton_ad_tk_Datlaimatkhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_ad_tk_Datlaimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ad_tk_DatlaimatkhauActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_ad_tk_Datlaimatkhau))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_ad_tk_Tentaikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ad_tk_Tentaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(jButton_ad_tk_Datlaimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable_ad_tk.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable_ad_tk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên tài khoản", "Loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Byte.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_ad_tk.setRowHeight(25);
        jTable_ad_tk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ad_tkMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_ad_tk);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_ad_TaikhoanLayout = new javax.swing.GroupLayout(jPanel_ad_Taikhoan);
        jPanel_ad_Taikhoan.setLayout(jPanel_ad_TaikhoanLayout);
        jPanel_ad_TaikhoanLayout.setHorizontalGroup(
            jPanel_ad_TaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ad_TaikhoanLayout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_ad_TaikhoanLayout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_ad_TaikhoanLayout.setVerticalGroup(
            jPanel_ad_TaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ad_TaikhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ad_TaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane_Admin.addTab("Tài khoản", jPanel_ad_Taikhoan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Admin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_ad_tkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ad_tkMouseClicked
        // lấy chỉ số dòng
        int selectedRow = jTable_ad_tk.getSelectedRow();
        // lấy giá trị từ DefaultTableModel
        DefaultTableModel model = (DefaultTableModel) jTable_ad_tk.getModel();
        String tenTaiKhoan = (String) model.getValueAt(selectedRow, 0);
        jTextField_ad_tk_Tentaikhoan.setText(tenTaiKhoan);
        int loai = (int) model.getValueAt(selectedRow, 1);
        LoadTableFoodByID(jComboBox1, loai);
        //        LoadListAcc();
    }//GEN-LAST:event_jTable_ad_tkMouseClicked

    private void jButton_ad_tk_DatlaimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ad_tk_DatlaimatkhauActionPerformed
        String user = jTextField_ad_tk_Tentaikhoan.getText();
        AdminServerController.ResetAcc(user);
        AdminServerController.LoadListAcc(jTable_ad_tk);
    }//GEN-LAST:event_jButton_ad_tk_DatlaimatkhauActionPerformed

    private void jTextField_ad_tk_TentaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ad_tk_TentaikhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ad_tk_TentaikhoanActionPerformed

    private void jButton_ad_tk_Xoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ad_tk_Xoa1ActionPerformed
        String user = jTextField_ad_tk_Tentaikhoan.getText();
        int type = Integer.valueOf(jComboBox1.getSelectedItem().toString().split(" -")[0].trim());
        AdminServerController.GetUpdateAcc(type, user);
        SetAccDefault();
        AdminServerController.LoadListAcc(jTable_ad_tk);
    }//GEN-LAST:event_jButton_ad_tk_Xoa1ActionPerformed

    private void jButton_ad_tk_XemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ad_tk_XemActionPerformed
        SetAccDefault();
        AdminServerController.LoadListAcc(jTable_ad_tk);
    }//GEN-LAST:event_jButton_ad_tk_XemActionPerformed

    private void jButton_ad_tk_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ad_tk_XoaActionPerformed
        String user = jTextField_ad_tk_Tentaikhoan.getText();
        AdminServerController.GetDeleteAcc(user);
        SetAccDefault();
        AdminServerController.LoadListAcc(jTable_ad_tk);
    }//GEN-LAST:event_jButton_ad_tk_XoaActionPerformed

    private void jButton_ad_tk_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ad_tk_ThemActionPerformed
        String user = jTextField_ad_tk_Tentaikhoan.getText();
        int type = Integer.valueOf(jComboBox1.getSelectedItem().toString().split(" -")[0].trim());
        AdminServerController.GetInsertAcc(user, type);
        SetAccDefault();
        AdminServerController.LoadListAcc(jTable_ad_tk);
//        order.LoadAgaint();
    }//GEN-LAST:event_jButton_ad_tk_ThemActionPerformed

    private void jTable_BananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_BananMouseClicked
        int selecedRow = jTable_Banan.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable_Banan.getModel();
        int id = (int) model.getValueAt(selecedRow, 0);
        jTextField3.setText(id + "");
        String name = (String) model.getValueAt(selecedRow, 1);
        jTextField4.setText(name);
        String status = (String) model.getValueAt(selecedRow, 2);
        jTextField5.setText(status);
    }//GEN-LAST:event_jTable_BananMouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        AdminServerController.loadTableFood(jTable_Banan);
        SetTableFoodDefault();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String name = jTextField4.getText();
        String status = jTextField5.getText();
        int id = Integer.valueOf(jTextField3.getText());
        AdminServerController.GetupdateTable(id, name, status);
        SetTableFoodDefault();
        AdminServerController.loadTableFood(jTable_Banan);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton_ta_dm_Xoa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ta_dm_Xoa3ActionPerformed
        int id = Integer.valueOf(jTextField3.getText());
        AdminServerController.GetDeleteTable(id);
        SetTableFoodDefault();
        AdminServerController.loadTableFood(jTable_Banan);
    }//GEN-LAST:event_jButton_ta_dm_Xoa3ActionPerformed

    private void jButton_ta_dm_Them3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ta_dm_Them3ActionPerformed
        String name = jTextField4.getText();
        String status = jTextField5.getText();
        AdminServerController.GetInsertTable(name, status);
        SetTableFoodDefault();
        AdminServerController.loadTableFood(jTable_Banan);
    }//GEN-LAST:event_jButton_ta_dm_Them3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTable_DanhmucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DanhmucMouseClicked
        int selectedRow = jTable_Danhmuc.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable_Danhmuc.getModel();
        int id = (int) model.getValueAt(selectedRow, 0);
        String name = (String) model.getValueAt(selectedRow, 1);
        jTextField1.setText(id + "");
        jTextField2.setText(name);
        //            GetListFoodCategory();
    }//GEN-LAST:event_jTable_DanhmucMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AdminServerController.GetListFoodCategory(jTable_Danhmuc);
        SetFoodCategoryDefault();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int id = Integer.valueOf(jTextField1.getText());
        String name = jTextField2.getText();
        AdminServerController.GetUpdateFoodCategory(id, name);
        AdminServerController.GetListFoodCategory(jTable_Danhmuc);
        SetFoodCategoryDefault();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton_ta_dm_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ta_dm_XoaActionPerformed
        int id = Integer.valueOf(jTextField1.getText());
        AdminServerController.GetDeleteFoodCategory(id);
        AdminServerController.GetListFoodCategory(jTable_Danhmuc);
        SetFoodCategoryDefault();
    }//GEN-LAST:event_jButton_ta_dm_XoaActionPerformed

    private void jButton_ta_dm_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ta_dm_ThemActionPerformed
        String name = jTextField2.getText();
        AdminServerController.GetInsertFoodCategory(name);
        AdminServerController.GetListFoodCategory(jTable_Danhmuc);
        SetFoodCategoryDefault();
    }//GEN-LAST:event_jButton_ta_dm_ThemActionPerformed

    private void jButton_ad_ta_XemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ad_ta_XemActionPerformed
        SetFoodDefault();
        AdminServerController.LoadListFood(jTable_Food);
    }//GEN-LAST:event_jButton_ad_ta_XemActionPerformed

    private void jButton_ad_ta_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ad_ta_SuaActionPerformed
        AdminServerController.LoadListFood(jTable_Food);
        int idFood = Integer.valueOf(jTextField_ad_ta_ID.getText());
        String name = jTextField_ad_ta_Tenmon.getText();
        int idCategory = Integer.valueOf(jComboBox_ad_ta_Danhmuc.getSelectedItem().toString().split(":")[0].trim());
        double price = Double.parseDouble(jSpinner_ad_ta_Gia.getValue() + "");
        System.out.println("IdFood" + idFood);
        System.out.println("Name" + name);
        System.out.println("IdCategory" + idCategory);
        System.out.println("Price" + price);

        AdminServerController.GetUpdateFood(idFood, name, idCategory, price);
        AdminServerController.LoadListFood(jTable_Food);
        SetFoodDefault();
    }//GEN-LAST:event_jButton_ad_ta_SuaActionPerformed

    private void jButton_ad_ta_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ad_ta_XoaActionPerformed
        //        AdminServerController.LoadListFood(jTable_Food);
        int idFood = Integer.valueOf(jTextField_ad_ta_ID.getText());
        AdminServerController.GetDeleteFood(idFood);
        SetFoodDefault();
        AdminServerController.LoadListFood(jTable_Food);
    }//GEN-LAST:event_jButton_ad_ta_XoaActionPerformed

    private void jButton_ad_ta_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ad_ta_ThemActionPerformed
        String name = jTextField_ad_ta_Tenmon.getText();
        int idCategory = Integer.valueOf(jComboBox_ad_ta_Danhmuc.getSelectedItem().toString().split(":")[0].trim());
        double price = Double.parseDouble(jSpinner_ad_ta_Gia.getValue() + "");

        AdminServerController.GetInsertFood(name, idCategory, price);

        SetFoodDefault();
        AdminServerController.LoadListFood(jTable_Food);
    }//GEN-LAST:event_jButton_ad_ta_ThemActionPerformed

    private void jComboBox_ad_ta_DanhmucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ad_ta_DanhmucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ad_ta_DanhmucActionPerformed

    private void jTextField_ad_ta_TenmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ad_ta_TenmonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ad_ta_TenmonActionPerformed

    private void jLabel_ta_TenmonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel_ta_TenmonAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_ta_TenmonAncestorAdded

    private void jlabel_ad_ta_TimthucanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlabel_ad_ta_TimthucanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlabel_ad_ta_TimthucanActionPerformed

    private void jButton_ad_ta_TimthucanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ad_ta_TimthucanActionPerformed
        String Name = jlabel_ad_ta_Timthucan.getText();
        AdminServerController.SearchFood(Name, jTable_Food);
    }//GEN-LAST:event_jButton_ad_ta_TimthucanActionPerformed

    private void jTable_FoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_FoodMouseClicked

        // Lấy chỉ mục hàng được chọn
        int selectedRow = jTable_Food.getSelectedRow();
        // Lấy dữ liệu từ mô hình của JTable
        DefaultTableModel model = (DefaultTableModel) jTable_Food.getModel();
        //        Object rowData = model.getDataVector().elementAt(selectedRow);            Lấy tất cả giá trị trong row
        int ID = (int) model.getValueAt(selectedRow, 0);
        jTextField_ad_ta_ID.setText(ID + "");
        int idCategory = (int) model.getValueAt(selectedRow, 2);
        AdminServerController.LoadFoodCategoryByID(jComboBox_ad_ta_Danhmuc, idCategory);
        Object name = model.getValueAt(selectedRow, 1);
        jTextField_ad_ta_Tenmon.setText(name.toString());
        Object price = model.getValueAt(selectedRow, 3);
        // Hiển thị dữ liệu lên JTextField
        jSpinner_ad_ta_Gia.setValue(price);
        //        LoadFoodCategoryIntoComboBox(jComboBox_ad_ta_Danhmuc);
    }//GEN-LAST:event_jTable_FoodMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.util.Date selectedDateCheckIn = jDateChooser_CheckIn.getDate();
        java.util.Date selectedDateCheckOut = jDateChooser_CheckOut.getDate();

        java.sql.Date checkIn = new java.sql.Date(selectedDateCheckIn.getTime());
        java.sql.Date checkOut = new java.sql.Date(selectedDateCheckOut.getTime());
        System.out.println(checkIn);
        System.out.println(checkOut);

        DefaultTableModel model1 = (DefaultTableModel) jTable_Thongke.getModel();
        model1.setRowCount(0);

        AdminServerController.ThongKe(checkIn, checkOut, jTable_Thongke);
    }//GEN-LAST:event_jButton1ActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_ad_ta_Sua;
    private javax.swing.JButton jButton_ad_ta_Them;
    private javax.swing.JButton jButton_ad_ta_Timthucan;
    private javax.swing.JButton jButton_ad_ta_Xem;
    private javax.swing.JButton jButton_ad_ta_Xoa;
    private javax.swing.JButton jButton_ad_tk_Datlaimatkhau;
    private javax.swing.JButton jButton_ad_tk_Them;
    private javax.swing.JButton jButton_ad_tk_Xem;
    private javax.swing.JButton jButton_ad_tk_Xoa;
    private javax.swing.JButton jButton_ad_tk_Xoa1;
    private javax.swing.JButton jButton_ta_dm_Them;
    private javax.swing.JButton jButton_ta_dm_Them3;
    private javax.swing.JButton jButton_ta_dm_Xoa;
    private javax.swing.JButton jButton_ta_dm_Xoa3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox_ad_ta_Danhmuc;
    private com.toedter.calendar.JDateChooser jDateChooser_CheckIn;
    private com.toedter.calendar.JDateChooser jDateChooser_CheckOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_ta_ID;
    private javax.swing.JLabel jLabel_ta_Tenmon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_ad_Banan;
    private javax.swing.JPanel jPanel_ad_Danhmuc;
    private javax.swing.JPanel jPanel_ad_Doanhthu;
    private javax.swing.JPanel jPanel_ad_Taikhoan;
    private javax.swing.JPanel jPanel_ad_Thucan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner_ad_ta_Gia;
    private javax.swing.JTabbedPane jTabbedPane_Admin;
    private javax.swing.JTable jTable_Banan;
    private javax.swing.JTable jTable_Danhmuc;
    private javax.swing.JTable jTable_Food;
    public javax.swing.JTable jTable_Thongke;
    private javax.swing.JTable jTable_ad_tk;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField_ad_ta_ID;
    private javax.swing.JTextField jTextField_ad_ta_Tenmon;
    private javax.swing.JTextField jTextField_ad_tk_Tentaikhoan;
    private javax.swing.JTextField jlabel_ad_ta_Timthucan;
    // End of variables declaration//GEN-END:variables

    void loadDateTimePickerBill() {
        LocalDate today = LocalDate.now();
        LocalDate fromDate = LocalDate.of(today.getYear(), today.getMonthValue(), 1);
        LocalDate toDate = fromDate.plusMonths(1).minusDays(1);

        Date fromDateSql = java.sql.Date.valueOf(fromDate);
        Date toDateSql = java.sql.Date.valueOf(toDate);
        System.out.println(fromDateSql);
        System.out.println(toDateSql);
        jDateChooser_CheckIn.setDate(fromDateSql);
        jDateChooser_CheckOut.setDate(toDateSql);
    }

    public void LoadTableFoodByID(JComboBox<String> comboBox, int id) {
        // Xóa các mục hiện tại trong ComboBox
        comboBox.removeAllItems();

        // Thêm các mục vào ComboBox
        comboBox.addItem("1 - Quản lý");
        comboBox.addItem("0 - Người dùng");

        // Duyệt qua các mục trong ComboBox để tìm Id tương ứng
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            String item = comboBox.getItemAt(i);
            int type = Integer.valueOf(item.split(" -")[0].trim());

            if (id == type) {
                // Nếu tìm thấy Id tương ứng, hiển thị mục đó
                comboBox.setSelectedItem(item);
                break;
            }
        }
    }

    public void SetFoodDefault() {
        jTextField_ad_ta_Tenmon.setText("");
        jSpinner_ad_ta_Gia.setValue(0);
        jTextField_ad_ta_ID.setText("");
    }

    public void SetTableFoodDefault() {
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }

    public void SetFoodCategoryDefault() {
        jTextField1.setText("");
        jTextField2.setText("");
    }

    public void SetAccDefault() {
        jTextField_ad_tk_Tentaikhoan.setText("");
    }
}
