/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

import Controller.InfomationController;
import DAOImpl.AccountDAO;
import DAOInterface.AccountInterface;
import Model.Account;
import java.rmi.Naming;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class InformationServer extends javax.swing.JFrame {

    /**
     * Creates new form InformationServer
     */
    private Account loginAccount;

    public Account getLoginAccount() {
        return loginAccount;
    }

    public void setLoginAccount(Account value) {
        loginAccount = value;
        changeAccount(loginAccount);
    }

    public InformationServer(Account acc) {
        initComponents();
        setLoginAccount(acc);
        System.out.println(acc.toString());
        setTitle("Thông tin tài khoản");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titledBorder1 = javax.swing.BorderFactory.createTitledBorder("");
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        passwordField_inf_Matkhaumoi = new SwingDesignt.PasswordField();
        passwordField_inf_Nhaplaimatkhaumoi = new SwingDesignt.PasswordField();
        textField_inf_Tennguoidung = new SwingDesignt.TextField();
        textField_inf_Tennguoidungmoi = new SwingDesignt.TextField();
        passwordField_inf_Matkhauhientai = new SwingDesignt.PasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN TÀI KHOẢN");

        passwordField_inf_Matkhaumoi.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        passwordField_inf_Matkhaumoi.setLabelText("Mật khẩu mới");
        passwordField_inf_Matkhaumoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordField_inf_MatkhaumoiActionPerformed(evt);
            }
        });

        passwordField_inf_Nhaplaimatkhaumoi.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        passwordField_inf_Nhaplaimatkhaumoi.setLabelText("Nhập lại mật khẩu mới");

        textField_inf_Tennguoidung.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        textField_inf_Tennguoidung.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        textField_inf_Tennguoidung.setLabelText("Tên người dùng");
        textField_inf_Tennguoidung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_inf_TennguoidungActionPerformed(evt);
            }
        });

        textField_inf_Tennguoidungmoi.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        textField_inf_Tennguoidungmoi.setLabelText("Tên người dùng mới");
        textField_inf_Tennguoidungmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_inf_TennguoidungmoiActionPerformed(evt);
            }
        });

        passwordField_inf_Matkhauhientai.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        passwordField_inf_Matkhauhientai.setLabelText("Mật khẩu");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Cập nhật");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(passwordField_inf_Nhaplaimatkhaumoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(70, 70, 70))))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passwordField_inf_Matkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textField_inf_Tennguoidung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textField_inf_Tennguoidungmoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passwordField_inf_Matkhauhientai, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(textField_inf_Tennguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textField_inf_Tennguoidungmoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordField_inf_Matkhauhientai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordField_inf_Matkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordField_inf_Nhaplaimatkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordField_inf_MatkhaumoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordField_inf_MatkhaumoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordField_inf_MatkhaumoiActionPerformed

    private void textField_inf_TennguoidungmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_inf_TennguoidungmoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_inf_TennguoidungmoiActionPerformed

    private void textField_inf_TennguoidungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_inf_TennguoidungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_inf_TennguoidungActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String user = textField_inf_Tennguoidung.getText();
        String newUser = textField_inf_Tennguoidungmoi.getText();
        String pass = new String(passwordField_inf_Matkhauhientai.getPassword());
        String newPass = "";
        String newPass2 = "";
        newPass = new String(passwordField_inf_Matkhaumoi.getPassword());
        System.out.println("newPass ở info: " + newPass);
        newPass2 = new String(passwordField_inf_Nhaplaimatkhaumoi.getPassword());
        UpdateAccount(user, newUser, pass, newPass, newPass2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InformationServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InformationServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InformationServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InformationServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                InformationServer inf = new InformationServer(Account acc);
//                inf.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private SwingDesignt.PasswordField passwordField_inf_Matkhauhientai;
    private SwingDesignt.PasswordField passwordField_inf_Matkhaumoi;
    private SwingDesignt.PasswordField passwordField_inf_Nhaplaimatkhaumoi;
    private SwingDesignt.TextField textField_inf_Tennguoidung;
    private SwingDesignt.TextField textField_inf_Tennguoidungmoi;
    private javax.swing.border.TitledBorder titledBorder1;
    // End of variables declaration//GEN-END:variables

    public void changeAccount(Account acc) {
        textField_inf_Tennguoidung.setText(acc.getUserName());
        textField_inf_Tennguoidung.setEditable(false);
    }

    public void UpdateAccount(String user, String newUser, String pass, String newPass, String newPass2) {
        try {
            AccountInterface userRmi = (AccountInterface) Naming.lookup("rmi://localhost:2004/Login");
            if (!newPass.equals(newPass2)) {
                JOptionPane.showConfirmDialog(null, "Vui lòng nhập lại đúng mật khẩu mới !", "Thông báo", JOptionPane.OK_OPTION);
            } else {
                if (userRmi.UpdateAccount(user, newUser, pass, newPass)) {
                    int ref = JOptionPane.showConfirmDialog(null, "Cập nhật thành công !", "Thông báo", JOptionPane.OK_OPTION);
                    if (ref == JOptionPane.OK_OPTION) {
                        this.dispose();
                    }
                } else {
                    JOptionPane.showConfirmDialog(null, "Vui lòng điền đúng mật khẩu ", "Thông báo", JOptionPane.OK_OPTION);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
